version: '3.0'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
    - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
    - db:/var/lib/mysql
  app-server:
    depends_on:
    - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: always
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
         }'
volumes:
  db: null